### ISSUE TITLE
Cryptic Error Loading Model

### ISSUE THREAD

**Issue by ss32** [BruceMacD/chatd#21]
```
Error: HTTP Error (500): {"error":"invalid version"}
```

And in the terminal

```
Ollama server is running
Error: HTTP Error (500): {"error":"invalid version"}
    at Ollama.generate (/home/user/deepLearning/chatd/chatd-linux-x64/resources/app/src/service/ollama/ollama.js:286:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Ollama.run (/home/scott/deepLearning/chatd/chatd-linux-x64/resources/app/src/service/ollama/ollama.js:177:5)
    at async run (/home/user/deepLearning/chatd/chatd-linux-x64/resources/app/src/service/ollama/ollama.js:329:10)
    at async IpcMainImpl.runOllamaModel (/home/scott/deepLearning/chatd/chatd-linux-x64/resources/app/src/api.js:36:5)
```

It was solved by upgrading `ollama` with `curl https://ollama.ai/install.sh | sh`

**Comment by ss32** [comment]
Just posting for visibility, closing.

**Comment by BruceMacD** [comment]
Thanks for documenting this.
