### ISSUE TITLE
always fetch failed

### ISSUE THREAD

**Issue by DravenYe** [BruceMacD/chatd#49]
when I click to upload the document, it always shows "fetch failed"

I have installed the version of v1.1.2,  chatd-windows-x64.zip

can anyone help me.........

![image](https://github.com/user-attachments/assets/4c1978c2-4919-4c88-8b6c-da3031655d0b)

**Comment by Shen-Yukang** [comment]
Hi, I am a freshman in `transformer. js`, I have met a similar problem when uploading a file. And I find the error was thrown by `embedding.js`.
<img width="1056" alt="44541735023221_ pic" src="https://github.com/user-attachments/assets/6ee94dde-aa00-4ff9-b12d-2f068319c97a" />

Is there any tips or advice on how to fixe this problem.
I appreciate your advice and assistance. Thank you!

**Comment by Shen-Yukang** [comment]
> Hi, I am a freshman in `transformer. js`, I have met a similar problem when uploading a file. And I find the error was thrown by `embedding.js`. <img alt="44541735023221_ pic" width="1056" src="https://private-user-images.githubusercontent.com/160222653/398345635-6ee94dde-aa00-4ff9-b12d-2f068319c97a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjM5MTMsIm5iZiI6MTczNTAyMzYxMywicGF0aCI6Ii8xNjAyMjI2NTMvMzk4MzQ1NjM1LTZlZTk0ZGRlLWFhMDAtNGZmOS1iMTJkLTJmMDY4MzE5Yzk3YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQwNzAwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDUzMDk1YWMyYjkxZDc0NTc5ZjY2NjA5MDcxYmJkMGNiM2VmMmQwOWNkN2I1ODI2ZGY0NDRmYWVjMzkyZTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4SlMmPUewvCHABB4CfP2FaHXb29ZGJxEAtdOYBqLbaI">
> 
> Is there any tips or advice on how to fixe this problem. I appreciate your advice and assistance. Thank you!

To clarify,  I selected "llama3.2" as local llm model.
Detailed error stacks as below:
```
 at embed (/Users/my/xxxxxx/src/service/embedding.js:52:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:447:9)
    at async MessagePort.<anonymous> (/Users/xxxxxx/src/service/worker.js:24:28) {
  [cause]: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:7967:28)
      at node:internal/deps/undici/undici:7925:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:7956:13)
      at process.processImmediate (node:internal/timers:476:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
Storing embeddings...
(node:4096) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'map')
    at VectorStore.addEmbeddings (/Users/xxxxxx/src/service/vector.js:25:30)
    at store (/Users/xxxxxx/src/service/vector.js:68:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Worker.<anonymous> (/Users/xxxxxx/src/api.js:156:7)

```
